### PR TITLE
Fail gracefully instead of infinite loop in face of primitive type al…

### PR DESCRIPTION
**Pull request by meirmaor**
…ias.
This is a mitigation (not a fix) for issues #169 , #76
(Pull request also for 3.4 branch) identical to PR #324 to 3.3

### CODE REVIEW

**Comment by seratch** [comment]
Thanks. If you have time, would you please write some tests to ensure that the change is efficient to avoid the infinite loop?

**Comment by meirmaor** [comment]
I can easily write a test which passes with the change(throws an exception) and enters an infinite loop without it. But I would normally prevent the infinite loop with a timeout which does not seem trivial with specs2 (which I'm not familiar with) and handling threads or futures myslef in a test also doesn't seem like the best way to go.
The reproduction case is simple:
type MyDouble = Double
case class Foo(a: List[MyDouble]) 

and try to serialize an instance of Foo

**Comment by jozic** [comment]
@meirmaor 
wouldn't it be good enough if a test passes with your fix and just hangs without? i anything breaks again the test will hang and this will signal something is wrong
@seratch wdyt? 

would be nice to have

**Comment by seratch** [comment]
>anything breaks again the test will hang and this will signal something is wrong

@jozic Yes, that's what I tend to do.

**Comment by meirmaor** [comment]
I added a test.feels kind of silly to write a test which can never fail.

**Comment by seratch** [comment]
@meirmaor Thanks. Looks good to me. If there is no objection, I'd like to merge this PR later.

**Comment by dsbos** [comment]
#397 seems related.

**Pull request merged**
