### PR TITLE
Executable: getMarkedAsPrimary should return true if isPrimaryCtor

### LINKED ISSUE #571: Extraction.decompose() returns different results between 3.6.0+ and 3.5.4
### json4s version
3.6.0, 3.5.4

### scala version
2.12.8

### jdk version
1.8.0_131

This issue occurs when existing a companion object's apply() method with more arguments than a case class.

## Failure symptoms

```scala
case class CompanionSample(s: String, i: Int)

object CompanionSample {
  def apply(str: String, i1: Int, i2: Int): CompanionSample = CompanionSample(str, i1 + i2)
}

import org.json4s.NoTypeHints
import org.json4s.jackson.Serialization
import org.scalatest.FunSuite

class Json4sTest extends FunSuite {
  test("xxx") {
    val obj = CompanionSample("hello", 1, 2)
    val json = Serialization.write(obj)(Serialization.formats(NoTypeHints))
    println(json)
    assert(json == """{"s":"hello","i":3}""")
  }
}
```

json4s 3.6.0
```
{}
```
json4s 3.5.4
```
{"s":"hello","i":3}
```

## Identified cause

https://github.com/json4s/json4s/pull/487 changed the return value of method `constructorsAndCompanion`. As a result, method `mostComprehensive` in class `ClassDescriptor` returns different results.

### constructorsAndCompanion
3.6.0
```
ArraySeq(
  ConstructorDescriptor(ArrayBuffer(ConstructorParamDescriptor(s,s,0,String,None), ConstructorParamDescriptor(i,i,1,int,None)),Executable(Constructor(public org.json4s.CompanionSample(java.lang.String,int))),false),
  ConstructorDescriptor(ArrayBuffer(ConstructorParamDescriptor(s,s,0,String,None), ConstructorParamDescriptor(i,i,1,int,None)),Executable(Method(public org.json4s.CompanionSample org.json4s.CompanionSample$.apply(java.lang.String,int))),false),
  ConstructorDescriptor(ArrayBuffer(ConstructorParamDescriptor(str,str,0,String,None), ConstructorParamDescriptor(i1,i1,1,int,None), ConstructorParamDescriptor(i2,i2,2,int,None)),Executable(Method(public org.json4s.CompanionSample org.json4s.CompanionSample$.apply(java.lang.String,int,int))),false)
)
```
3.5.4
```
ArraySeq(
  ConstructorDescriptor(ArrayBuffer(ConstructorParamDescriptor(s,s,0,String,None), ConstructorParamDescriptor(i,i,1,int,None)),Executable(Constructor(public org.json4s.CompanionSample(java.lang.String,int))),false)
)
```

### descriptor.mostComprehensive.map(_.name)
https://github.com/json4s/json4s/blob/v3.6.0/core/src/main/scala/org/json4s/Extraction.scala#L120

3.6.0
```
ArrayBuffer(str, i1, i2)
```
3.5.4
```
ArrayBuffer(s, i)
```

I haven't found a solution yet. As a temporary workaround, it works to add a field serializer for a case class to the formats, or mark the primary constructor.

### PR DESCRIPTION
**Pull request by shanielh**
Fixes #571

### CODE REVIEW

**Comment by seratch** [comment]
Wow, what a prompt work! LGTM. Thank you very much.

**Comment by seratch** [comment]
I'll release a new version including this change within a few hours.

**Comment by seratch** [comment]
I will create a backport PR to 3.6 series for the release.

**Comment by shanielh** [comment]
@seratch Thank you.

**Pull request merged**
