### PR TITLE
Add short2jvalue

### PR DESCRIPTION
**Pull request by ponkotuy**

### CODE REVIEW

**Comment by dozed** [comment]
Thanks.

**Comment by dozed** [comment]
Do we also want to support Byte?

**Comment by dozed** [comment]
Hm, it seems Short, Byte and Char can already be implicitly converted to a JValue. It compiles, but Intellij marks it as an error.

Why did you add the implicit conversion?

**Comment by dozed** [comment]
@rossabaker suggested that the implicit conversion could be useful in the case of collections, which it actually is. @ponkotuy do you want to create a PR with additional conversions for Byte and Char?

```scala
implicit def short2jvalue(x: Short): JValue = JInt(x)
implicit def byte2jvalue(x: Byte): JValue = JInt(x)
implicit def char2jvalue(x: Char): JValue = JInt(x)

def check(jv: JValue) = jv

val s: Short = 2
val b: Byte = 2
val c: Char = 2

check(s)
check(b)
check(c)

val l1: List[Short] = List(s)
val l2: List[Byte] = List(b)
val l3: List[Char] = List(c)

check(l1)
check(l2)
check(l3)

// without the implicit conversions the compiler would not be able to convert List[_] to JValue
// Error: type mismatch; found: List[Short] required: org.json4s.JValue
// Error: type mismatch; found: List[Byte] required: org.json4s.JValue
// Error: type mismatch; found: List[Char] required: org.json4s.JValue
```

**Comment by ponkotuy** [comment]
I'll do so right away.

**Pull request merged**
