### PR TITLE
Use default values on the only c'tor or the one marked using `PrimaryConstructor`

### PR DESCRIPTION
**Pull request by shanielh**
Added test too :)

### CODE REVIEW

**Comment by seratch** [comment]
Sorry for my late response. LGTM.

**Comment by shanielh** [comment]
@seratch Thanks for merging! Do you have a plan to release?

**Comment by seratch** [comment]
@shanielh I will release 3.6.0-M3 soon.

**Comment by seratch** [comment]
I just released version 3.6.0-M3. https://oss.sonatype.org/content/repositories/releases/org/json4s/json4s-core_2.12/3.6.0-M3/

**Pull request merged**
