### PR TITLE
[Feature] Handling of case objects (singletons)

### PR DESCRIPTION
**Pull request by geggo98**
Enables the handling of "case object" in addition to "case class". The code contains a test class with a simple example: a tree that can have value nodes (case class) and empty nodes (case object).

### CODE REVIEW

**Comment by seratch** [comment]
I'm not sure many people need this feature.

**Comment by geggo98** [comment]
@seratch Case objects are used all over the place. Every time you have a case class without a parameter, you should use a case object. Often they are used as kind of "marker" in recursive data structures: The end of a linked list or the leafs of a tree. You also can use them signal an empty structure: An empty list, a tree of depth zero, a graph without nodes. In the Scala standard library, Nil is a case object.

When you want do de-serialize such structures, you need support for case objects.

Some people argue, that one should use case objects instead of enumerations. So to let these people the choice between these pattern, again support for case objects is needed.

**Comment by seratch** [comment]
@geggo98 Thanks. I wonder exposing Scala singleton objects' name (e.g. `EmptyLeaf$`) as jsonClass is fine. I basically agree using case objects in json4s would be useful.

**Comment by geggo98** [comment]
@seratch Good point. The `$` is indeed a bit dirty, as it is a technical artifact from the underlying Java language. For me it was the simplest solution that immediately solved my problem. If you have a better idea, please tell me. I will gladly adapt my code.

**Pull request merged**
