### PR TITLE
Allow missing optional values even with strictOptionParsing

### PR DESCRIPTION
**Pull request by tjarvstrand**
Fixes https://github.com/json4s/json4s/issues/730

### CODE REVIEW

**Comment by magnolia-k** [comment]
@tjarvstrand 
It seems that this change should be reflected in the README as well.

**Comment by tjarvstrand** [comment]
Are you sure? I can add it but I think it could actually make things less clear. IMHO it's the current behaviour that confuses things. 

`json4s` is opinionated about `Option`s (which is good) and considers their use as a way of saying that fields are optional in the JSON data. When using `strictOptionParsing` that is no longer the case. `Option`s are suddenly treated as mandatory even though though they are explicitly marked as optional. Moreover there is no mention of this behaviour in the README. 

This is a summary of the current behaviour:
| Value        | `strictOptionParsing`          | Result  |
| ------------- |:-------------:| -----:|
missing | `false` | None
valid |`false` | Some
invalid | `false` | None
missing | `true` | MappingException
valid |`true` | Some
invalid | `true` | MappingException

This PR will change the behaviour to the following:
| Value        | `strictOptionParsing`          | Result  |
| ------------- |:-------------:| -----:|
missing | `false` | None
valid |`false` | Some
invalid | `false` | None
missing | `true` | None
valid |`true` | Some
invalid | `true` | MappingException

This limits the effect of `strictOptionParsing` to the handling of invalid data and makes things more straight forward (if you ask me)

**Comment by magnolia-k** [comment]
I see, you're right, that's a good point. I think the merge will be fine as is.
(The README is lacking some description about the behavior, but that's another story.

@mccartney @seratch @xuwei-k 

please review this PR!

**Comment by tjarvstrand** [comment]
@mccartney @seratch @xuwei-k ping :)

**Review by mccartney — APPROVED** [review]

**Comment by tjarvstrand** [comment]
@mccartney Thanks! :) Is there any timeline for the 3.7.0 release? Lots of good stuff in there now :)

**Comment by mccartney** [comment]
I'd be interested too. I am not sure.

I don't have permissions, nor know the context to decide.

**Comment by tjarvstrand** [comment]
Too bad. Thanks anyway!

**Comment by mccartney** [comment]
But I hope @seratch, @xuwei-k or @magnolia-k should know.

**Comment by magnolia-k** [comment]
@seratch @xuwei-k 

Should we release the 3.7-M10?

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/releases/tag/v3.7.0-M10

**Comment by tjarvstrand** [comment]
@xuwei-k Thank! What is the M-label?

**Comment by mccartney** [comment]
I guess it stands for Milestone. Some other versioning schemes call it a RC (release candidate). So it's a 10th semi-release before full 3.7.0 release.

**Comment by tjarvstrand** [comment]
Ah, cool. I've been racking my brain about that one for a long time :D

**Pull request merged**
