### PR TITLE
Add custom serializer to serde subtypes based on field value

### PR DESCRIPTION
**Pull request by ncolomer**
Refers to json4s/json4s#284

### CODE REVIEW

**Comment by ncolomer** [comment]
Although it runs, there is still a problem in this implementation: I had to rely on a [`native.Serialization`](https://github.com/json4s/json4s/pull/454/files#diff-fe07e0810e939f34dadce33d41da469eR10) format internally since the user-provided formatter causes `StackOverflow` errors (the supertype always match).

@xuwei-k @seratch do you see a better way?
Ping @rauanmayemir

**Comment by ncolomer** [comment]
Anybody? :-)

**Comment by rauanmayemir** [comment]
Hey @ncolomer 
I'll be able to check this in couple weeks.

**Comment by seratch** [comment]
Sorry for being so late. LGTM.

**Pull request merged**
