### PR TITLE
Support Java8 Date & Time API

### LINKED ISSUE #477: Java8 Date & Time API support
Is there any chance to add Java8 Date & Time API support as same as Joda-Time support in ext module?

I found old issue (#271) and pull request (#243), but the pull request was rejected to keep binary compatibility. How about adopting it in the current development branch? or as an another module?

### PR DESCRIPTION
**Pull request by takezoe**
Fixes #477 

Original pull request is #243 and I added following modifications, Thanks to @DanielaSfregola!

- Improved the timezone handling. It makes possible to handle the timezone correctly when the date format is customized.
- Extracted `DateParser` and `ClassSerializer` as an individual class (or object) and made public `ClassType` because they are useful to make new serializers. It's nice if they are able to be used by users.

### CODE REVIEW

**Comment by xuwei-k** [comment]
please fix `jdk: ` settings in `.travis.yml`

**Comment by takezoe** [comment]
Hmm... Should I also update cross build configuration in sbt?

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/blob/cf4002e28951604d5e288d3e9e42b5c3c5a7cdde/project/build.scala#L76-L79 🙏

**Comment by takezoe** [comment]
@xuwei-k All tests passed!

**Pull request merged**
